### ISSUE TITLE
Not working with iOS 12

### ISSUE THREAD

**Issue by ghost** [gilshahar7/AVLock#1]
The tweak doesn’t work on iOS 12. Will you update it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gilshahar7** [comment]
Thanks for contacting me, in fact I just finished future restoring my
device to iOS 12 and I’ll work on updating all of my tweaks, stay tuned.

**Comment by gilshahar7** [comment]
Okay I got it working on iOS 12. The update will be on the Big boss repo
after they review and upload it, so check your Cydia updates in a day or so.

**Comment by ghost** [comment]
Wow, so efficient. Thank you.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
