### ISSUE TITLE
Not working on iOS 13

### ISSUE THREAD

**Issue by the-eric-kwok** [gilshahar7/AVLock#2]
I’m running iOS 13.2 with checkra1n jailbreak and I found this tweak doesn’t work, the lock icon didn’t even show up. 
Thank you for developing such an useful tweak, will you update it for iOS 13?

**Comment by gilshahar7** [comment]
Hey thanks for reaching out, i just updated the tweak. 
Also, it will be hosted on Packix from now on, so please download the latest version (1.0.4) from there.
it will be available soon. in the meantime you can install the 1.0.4 deb file that i uploaded here.

**Comment by the-eric-kwok** [comment]
Thanks man! Well done!

**Comment by the-eric-kwok** [comment]
It works great on my iPad, but I found that on my iPhone 6s, when I tapped the lock button, it will turn into portrait but not lock in landscape mode... Is that how it works or is it a bug?
I wish it could actually “lock” in what I want but not “force” me to use portrait mode. Is that gonna work?
And thanks again for replying 😄

**Comment by gilshahar7** [comment]
As far as i know, this is stock iOS behaviour. AVLock is just an extension to the same button found in the control center.

Only ipads gets to keep landscape locking. iPhones can only lock portrait. 

Maybe a tweak can add this functionality. i know it was possible in the past with Activator.
